Vagrant.configure("2") do |config|
	
	numOfManagerVMs = 1
	numOfWorkerVMs = 1

	managerVmMem = 6000
	workerVmMem = 6000

	vmsGroupName = "docker"

	vmsImageName = "centos/7"

	ipAddressPrefix = "192.168.57.16"

	#creates docker manager VMs
	(1..numOfManagerVMs).each do |i|
		config.vm.define "mgr#{i}" do |node|
			node.vm.box = vmsImageName
			node.vm.hostname = "mgr#{i}"
			node.vm.network :private_network, ip: "#{ipAddressPrefix}#{i}"
			node.vm.synced_folder "sharedFolder/", "/sharedFolder", create: true
			
			node.vm.provider :virtualbox do |v|
				v.customize ["modifyvm", :id, "--name", "mgr#{i}"]
				v.customize ["modifyvm", :id, "--groups", "/#{vmsGroupName}"]
			    v.customize ["modifyvm", :id, "--memory", managerVmMem]
			end
			
			node.vm.provision "shell", inline: <<-SHELL
				yum install -y wget
				wget -qO- https://test.docker.com/ | sh
				curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
				chmod +x /usr/local/bin/docker-compose
			SHELL
			
		end
	end
	
	#creates docker worker VMs
	(1..numOfWorkerVMs).each do |i|
		machineNum = i
		machineName = "wrk#{machineNum}"
		config.vm.define "#{machineName}" do |node|
			node.vm.box = vmsImageName
			node.vm.hostname = "#{machineName}"
			node.vm.network :private_network, ip: "#{ipAddressPrefix}#{i + numOfManagerVMs}"
			node.vm.synced_folder "sharedFolder/", "/sharedFolder", create: true
			
			node.vm.provider :virtualbox do |v|
				v.customize ["modifyvm", :id, "--name", "#{machineName}"]
				v.customize ["modifyvm", :id, "--groups", "/#{vmsGroupName}"]
				v.customize ["modifyvm", :id, "--memory", workerVmMem]
			end
			
			node.vm.provision "shell", inline: <<-SHELL
				yum install -y wget
				wget -qO- https://test.docker.com/ | sh
				curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
				chmod +x /usr/local/bin/docker-compose
			SHELL
			
		end
	end

end